name: Backend CI

on:
  pull_request:
    paths: ['backend/**']
  push:
    branches: [main]
    paths: ['backend/**']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy
      
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: backend
      
      - name: Install cargo-lambda
        run: pip install cargo-lambda
      
      - name: Check formatting
        run: cargo fmt --manifest-path backend/Cargo.toml --all -- --check
      
      - name: Lint with clippy
        run: cargo clippy --manifest-path backend/Cargo.toml --all-targets -- -D warnings
      
      - name: Run tests
        run: cargo test --manifest-path backend/Cargo.toml --workspace
      
      - name: Build for Lambda (ARM64)
        run: cargo lambda build --arm64 --release --manifest-path backend/Cargo.toml
      
      - name: Upload Lambda artifacts
        uses: actions/upload-artifact@v4
        if: github.ref == 'refs/heads/main'
        with:
          name: lambda-binaries-${{ github.sha }}
          path: backend/target/lambda/**/*.zip
          retention-days: 7
