name: Tests Exhaustivos

on:
  pull_request:
  push:
    branches: [main]

jobs:
  backend-tests:
    name: Backend Tests (Rust)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: backend
      
      - name: Run tests
        run: cargo test --manifest-path backend/Cargo.toml --workspace --verbose
      
      - name: Generate coverage
        run: |
          cargo install cargo-tarpaulin || true
          cargo tarpaulin --manifest-path backend/Cargo.toml --workspace --out Lcov --output-dir coverage
      
      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage/lcov.info
          flags: backend

  frontend-unit:
    name: Frontend Unit Tests (Vitest)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json
      
      - run: npm -w frontend ci
      
      - name: Run tests
        run: npm -w frontend run test -- --coverage
      
      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          files: ./frontend/coverage/lcov.info
          flags: frontend-unit

  e2e-tests:
    name: E2E Tests (Playwright)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      
      - run: npm -w frontend ci
      
      - run: npm -w frontend run build
        env:
          VITE_API_BASE: https://mock-api.test.com
          VITE_COGNITO_DOMAIN: https://mock.auth.amazoncognito.com
      
      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium
      
      - name: Run E2E tests
        run: npm -w frontend exec playwright test
      
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: frontend/playwright-report/
          retention-days: 7
      
      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-screenshots
          path: frontend/test-results/
          retention-days: 7
